#1 Add location picking feature
oriash93/AutoClicker pull request #68
Opened 2022-09-03 22:43 UTC by reloaded

- Added a "Capture Mouse Coordinates" button next to the X, Y coordinate textboxes allowing the user to capture screen coordinates using the mouse. The captured coordinates will be automatically prefilled in the aforementioned textboxes.
- Added a new CaptureMouseScreenCoordinatesWindow that overlays a partially transparent window across all available screens/monitors.
- CaptureMouseScreenCoordinatesWindow exposes a public event that MainWindow hooks in to to receive the user's mouse coordinates upon mouse click.

![image](https://user-images.githubusercontent.com/1775239/188289720-4145cd39-44cf-4603-86ad-a838f8a08cb5.png)

The following scenarios have been tested.
- 1 monitor.
- 2 monitors, horizontally (see below).
![image](https://user-images.githubusercontent.com/1775239/188289666-ee19247d-898b-4d3c-8807-1b5efae00ddb.png)

- 2 monitors, vertically (see below).
![image](https://user-images.githubusercontent.com/1775239/188289677-7fc087c2-0ba9-414b-9f10-f3c92ea714b0.png)

- 2 monitors, horizontally, but one has a Y offset (see below).
![image](https://user-images.githubusercontent.com/1775239/188289662-441f2fb9-e529-4701-93bd-a670ff3c0902.png)

- 2 monitors, vertically, but one has a X offset (see below).
![image](https://user-images.githubusercontent.com/1775239/188289700-f870d20c-140e-4e58-80dc-051c82b92f50.png)

The following scenarios have not been tested.
- 3 monitors, where 2 are horizontal and the 3rd is vertically stacked above/under the others.

2022-09-04 02:30 UTC, reloaded commented
@oriash93  bringing your attention to this PR, hopefully it can get merged in relatively soon as it's a helpful feature when wanting to click in a specific spot on screen.

2022-09-04 03:56 UTC, reloaded commented
Based on my testing the only bug I found is for the rare scenario where the user's primary screen is configured with a negative offset.

In the horizontal layout configured as seen below (screen 1 is primary).

![image](https://user-images.githubusercontent.com/1775239/188296165-4497548c-7bdf-453e-a877-c30691d722bf.png)

The bug is that the capture window does not draw fully across screen 2. See below.

![image](https://user-images.githubusercontent.com/1775239/188296547-50a08758-e198-4580-9884-6a70966168c8.png)

A note about the above image: For some reason the Snipping Tool and Print Screen functions capture things backwards. In the screenshot showing the bug the screen where the window was only rendered halfway across is Screen 2 in the display configuration screenshot...

In a vertical layout configured as seen below (screen 1 is primary).

![image](https://user-images.githubusercontent.com/1775239/188296263-08f9f7ba-9a3e-4212-bf31-d46256aafa95.png)

The bug is that the capture window does not draw fully across screen 1. See below.

![image](https://user-images.githubusercontent.com/1775239/188296571-8bc093b5-d3ba-4351-94c7-5c24b55e3283.png)

2022-09-04 12:59 UTC, oriash93 commented
Hey @reloaded! first of all, thanks a lot for the PR!
I will take a look at it ASAP

2022-09-07 11:05 UTC, oriash93 requested changes
Partial review in the meantime, great work so far!

2022-09-07 11:05 UTC, oriash93 commented on AutoClicker/AutoClicker.csproj
> +    <Resource Include="Resources\Icons\location-crosshairs-solid.ico" />
two questions regarding this:
1. did you create the icon yourself, or did you import it from somewhere?
2. can you please make sure it's defined like the other resources? (configured in the Properties window in VS)

2022-09-07 11:05 UTC, oriash93 commented on AutoClicker/Utils/Constants.cs
> +﻿using System.Drawing;
this import is unused here, please remove it

2022-09-07 11:05 UTC, oriash93 commented on AutoClicker/Views/CaptureMouseScreenCoordinatesWindow.xaml
> +        Title="CaptureMouseScreenCoordinatesWindow" Height="450" Width="800"
should we limit the height and width here?

2022-09-07 11:05 UTC, oriash93 commented on AutoClicker/Views/CaptureMouseScreenCoordinatesWindow.xaml.cs
> +        public event EventHandler<System.Drawing.Point> OnCoordinatesCaptured;
simplify System.Drawing.Point by adding an import please

2022-09-10 06:05 UTC, reloaded commented on AutoClicker/AutoClicker.csproj
> +    <Resource Include="Resources\Icons\location-crosshairs-solid.ico" />
1. The icon is a FontAwesome free SVG icon converted to ICO format. 
https://fontawesome.com/icons/location-crosshairs?s=solid&f=sharp 

2. Sure.

2022-09-10 06:08 UTC, reloaded commented on AutoClicker/Views/CaptureMouseScreenCoordinatesWindow.xaml
> +        Title="CaptureMouseScreenCoordinatesWindow" Height="450" Width="800"
The height and width here should not be limited, it's sized dynamically in the code behind. This window view spans all screens from corner to corner to capture the mouse click location for the auto clicker. Let me know if I misunderstood you here.

2022-09-10 06:18 UTC, reloaded commented
@oriash93  I took care of your suggestions & requests. Go ahead and give it another look.

If Github gives you the option to do so, you should ensure this PR is merged in via a Squash merge. That way your main branch only has a single commit that brings in this feature and keeps your commit history clean.

2022-09-27 17:42 UTC, reloaded commented
@oriash93  bump, do you have time to finish reviewing this PR?

2022-11-09 08:06 UTC, oriash93 commented
Hey @reloaded sorry for the delay. I plan to review and merge by the end of this week :)

2022-11-09 18:21 UTC, reloaded commented
Great.

2022-11-19 15:54 UTC, oriash93 approved these changes

2022-11-19 15:56 UTC, merged

2022-11-19 15:58 UTC, oriash93 commented
@reloaded Thank you so much for your contribution!